[versions]
# SDK & Gradle
agp = "8.13.0"
kotlin = "2.2.10"

# Compose
compose-bom = "2025.08.01" # BOM aggiornata

# AndroidX
core-ktx = "1.17.0"
lifecycle = "2.9.3"
activity-compose = "1.10.1"
navigation-compose = "2.9.3"


retrofit = "3.0.0"


# Room
room = "2.7.2"
ksp = "2.2.10-2.0.2"

# Hilt
hilt = "2.57.1"
hilt-ext = "1.2.0"

# DataStore
datastore = "1.1.7"

# Material
material3 = "1.3.2"
ui-text = "1.9.0"
runtime-livedata = "1.9.0"
foundation = "1.9.0"
runtime = "1.9.0"
room-compiler = "2.8.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
# Core
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }

# Lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-ext" }

# DataStore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Debug/Test
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "ui-text" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtime-livedata" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-compiler" }
